### ISSUE TITLE
Incorrect Mailto Link

### ISSUE THREAD

**Issue by guitaristtom** [MykalMachon/mykal.codes#80]
The mailto link is not formatted correctly. It's missing the `//` after the colon.

https://github.com/MykalMachon/mykal.codes/blob/359cdb6928d2023adf2229c5200bab56139aac6d/www/src/utils/rss.ts#L12

**Comment by MykalMachon** [comment]
@guitaristtom, after looking at this, it's not incorrectly formatted! I think mailto:<email> is the right move. 

[See this article from CSS tricks](https://css-tricks.com/snippets/html/mailto-links/), after testing mailto links do work fine without the `//`, I can't find anything saying you should have those slashes in there.
