### ISSUE TITLE
"Read the full post" link is missing a slash

### ISSUE THREAD

**Issue by ThomasHineXYZ** [MykalMachon/mykal.codes#88]
Looking at my RSS reader, it looks like the `Read the full post on the site` link is missing a slash.

The link came out like this: `https://mykal.codesposts/intro-to-llm-andrej`

https://github.com/MykalMachon/mykal.codes/blob/d35845d30173fd8e7dd14d73cd84b220d0dab86e/website/src/pages/feeds/posts.xml.ts#L16C1-L16C1

**Comment by MykalMachon** [comment]
closed by #89
